/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ipcbqjrceyqleuaufier"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwY2JxanJjZXlxbGV1YXVmaWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMzNjIzNzMsImV4cCI6MjA5ODkzODM3M30.SsZB9I-LVFDYpPhHIsWSFjhIfRHXIUmB-s7dWxhMEnA"