-- EcoGo! catalog seed, generated from src/data/products.csv (via the app's CSV importer)
-- and the resource lists in App.tsx / MapTab.tsx. Ids match the CSV and the app's hardcoded
-- per-product explanations (ids 1-7), so they are inserted explicitly.

insert into public.categories (name) values
  ('Baby Care'),
  ('Beverages'),
  ('Bread'),
  ('Breakfast'),
  ('Cleaning'),
  ('Condiments'),
  ('Dairy'),
  ('Frozen'),
  ('Meat'),
  ('Medicine'),
  ('Personal Care'),
  ('Pet Food'),
  ('Snacks');

insert into public.products (id, barcode, name, brand, category_id, description, ingredients, image_url, keywords, health_score, environment_score, ethics_score, transparency_score) values
  (1, '028400315035', 'Lay''s Classic Potato Chips 8oz', 'Frito-Lay / PepsiCo', (select id from public.categories where name = 'Snacks'), 'Salted potato chips fried in vegetable oil. A classic American snack.', 'Potatoes, Vegetable Oil (Sunflower, Corn, and/or Canola Oil), Salt', '', array['chips', 'lays', 'snacks', 'potato', 'crisps']::text[], 62, 42, 55, 55),
  (2, '037000869870', 'Tide PODS Laundry Detergent 42ct', 'Procter & Gamble', (select id from public.categories where name = 'Cleaning'), 'Concentrated 3-in-1 laundry detergent pods. Detergent + stain remover + brightener.', 'Anionic surfactants, nonionic surfactants, enzymes, fragrance, methylisothiazolinone, 1,4-dioxane (trace)', '', array['tide', 'laundry', 'detergent', 'pods', 'cleaning', 'wash']::text[], 38, 32, 38, 28),
  (3, '602652171756', 'KIND Bars Variety Pack 12ct', 'KIND Snacks (Mars Inc.)', (select id from public.categories where name = 'Snacks'), 'Whole nut and fruit bars. Non-GMO, gluten-free, no artificial flavors.', 'Almonds, honey, glucose syrup, palm kernel oil, soy lecithin, sea salt', '', array['kind', 'bars', 'snacks', 'granola', 'healthy', 'nuts', 'protein']::text[], 81, 68, 72, 78),
  (4, '052000045010', 'Gatorade Thirst Quencher 12×20oz', 'PepsiCo', (select id from public.categories where name = 'Beverages'), 'Sports hydration drink with electrolytes. Replaces fluids and electrolytes lost during exercise.', 'Water, sucrose, dextrose, citric acid, natural flavor, salt, sodium citrate, monopotassium phosphate, Red 40, Blue 1', '', array['gatorade', 'sports drink', 'beverage', 'drink', 'electrolyte', 'hydration']::text[], 55, 45, 55, 52),
  (5, '732913222019', 'Seventh Generation Free & Clear Laundry', 'Seventh Generation (Unilever)', (select id from public.categories where name = 'Cleaning'), 'Plant-derived laundry detergent. Free of fragrances, dyes, and optical brighteners. B Corp certified.', 'Water, sodium gluconate, sodium lauryl sulfate (plant-derived), lauramine oxide, sodium citrate, citric acid', '', array['seventh generation', 'laundry', 'detergent', 'natural', 'eco', 'green', 'plant', 'free and clear']::text[], 92, 88, 88, 92),
  (6, '044700032085', 'Oscar Mayer Classic Beef Hot Dogs 10ct', 'Kraft Heinz', (select id from public.categories where name = 'Meat'), 'Classic beef franks made with mechanically separated turkey and pork. Contains sodium nitrite.', 'Beef, water, corn syrup, dextrose, salt, sodium phosphates, sodium erythorbate, sodium nitrite', '', array['hot dogs', 'oscar mayer', 'beef', 'meat', 'wieners', 'franks']::text[], 28, 22, 36, 40),
  (7, '049000006421', 'Diet Coke 12-Pack Cans', 'The Coca-Cola Company', (select id from public.categories where name = 'Beverages'), 'Zero-calorie cola sweetened with aspartame. Distinct crisp taste with 46mg of caffeine per can.', 'Carbonated water, caramel color, aspartame, phosphoric acid, potassium benzoate, natural flavors, citric acid, caffeine', '', array['diet coke', 'coca cola', 'soda', 'diet', 'beverage', 'cola', 'coke', 'zero calorie']::text[], 48, 38, 52, 55),
  (8, '049000028905', 'Coca-Cola Classic 12-Pack Cans', 'The Coca-Cola Company', (select id from public.categories where name = 'Beverages'), 'The original cola. 39g of sugar per can, 140 calories.', 'Carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine', '', array['coca cola', 'coke', 'soda', 'cola', 'beverage', 'classic']::text[], 40, 32, 45, 52),
  (9, '048500205082', 'Tropicana Pure Premium Orange Juice 52oz', 'PepsiCo', (select id from public.categories where name = 'Beverages'), '100% pure squeezed pasteurized orange juice. No added sugar or preservatives.', '100% Orange Juice', '', array['tropicana', 'orange juice', 'juice', 'beverage', 'oj', 'vitamin c']::text[], 72, 58, 55, 68),
  (10, '070847011443', 'Monster Energy Original 4pk 16oz', 'Monster Beverage Corp.', (select id from public.categories where name = 'Beverages'), 'Energy drink with B vitamins and caffeine blend. 160mg caffeine per can.', 'Carbonated water, sucrose, glucose, citric acid, taurine, sodium citrate, panax ginseng extract, B vitamins, caffeine, artificial flavor', '', array['monster energy', 'energy drink', 'caffeine', 'beverage', 'energy']::text[], 28, 32, 38, 42),
  (11, '613008106690', 'AriZona Green Tea 23oz Can', 'AriZona Beverages', (select id from public.categories where name = 'Beverages'), 'Green tea with ginseng and honey. Iconic oversized can.', 'Brewed green tea, high fructose corn syrup, honey, citric acid, ascorbic acid, natural flavors, panax ginseng extract', '', array['arizona', 'green tea', 'tea', 'beverage', 'iced tea', 'ginseng']::text[], 62, 55, 62, 58),
  (12, '611269356427', 'Red Bull Energy Drink 4pk 8.4oz', 'Red Bull GmbH', (select id from public.categories where name = 'Beverages'), 'Original energy drink with taurine and B vitamins. 80mg caffeine per can.', 'Carbonated water, sucrose, glucose, citric acid, taurine, sodium bicarbonate, magnesium carbonate, B vitamins, caffeine, natural flavors', '', array['red bull', 'energy drink', 'caffeine', 'beverage', 'wings', 'energy']::text[], 32, 42, 52, 58),
  (13, '028400064057', 'Doritos Nacho Cheese Party Size 14.5oz', 'Frito-Lay / PepsiCo', (select id from public.categories where name = 'Snacks'), 'Corn tortilla chips with bold nacho cheese seasoning.', 'Corn, vegetable oil (corn, canola, and/or sunflower oil), maltodextrin, salt, cheddar cheese, whey, monosodium glutamate, buttermilk, romano cheese, artificial color (Yellow 6), natural flavor', '', array['doritos', 'nacho cheese', 'chips', 'corn chips', 'snacks', 'tortilla chips']::text[], 45, 35, 48, 52),
  (14, '044000030438', 'Oreo Original Cookies 14.3oz', 'Nabisco / Mondelez', (select id from public.categories where name = 'Snacks'), 'Classic chocolate sandwich cookies with creme filling.', 'Enriched flour, sugar, palm and/or canola oil, cocoa (processed with alkali), high fructose corn syrup, leavening, salt, soy lecithin, natural and artificial flavor, chocolate', '', array['oreo', 'cookies', 'snacks', 'chocolate', 'sandwich cookie', 'biscuit']::text[], 48, 42, 48, 55),
  (15, '028400118705', 'Cheetos Crunchy 8.5oz', 'Frito-Lay / PepsiCo', (select id from public.categories where name = 'Snacks'), 'Crunchy cheese-flavored corn puffs. Contains Yellow 6 artificial color.', 'Enriched corn meal, vegetable oil, cheese seasoning (whey, cheddar cheese, canola oil, salt, buttermilk, natural and artificial flavor, monosodium glutamate, Yellow 6)', '', array['cheetos', 'cheese puffs', 'snacks', 'crunchy', 'corn snacks', 'frito-lay']::text[], 35, 32, 45, 48),
  (16, '016000280939', 'Nature Valley Crunchy Granola Bars 12ct', 'General Mills', (select id from public.categories where name = 'Snacks'), 'Whole grain oat bars with natural honey. Non-GMO project verified.', 'Whole grain rolled oats, sugar, canola oil, honey, crisp rice, salt, soy lecithin, baking soda', '', array['nature valley', 'granola bars', 'oats', 'snacks', 'bars', 'healthy', 'whole grain']::text[], 72, 62, 65, 70),
  (17, '029000017405', 'Planters Deluxe Mixed Nuts 15.25oz', 'Kraft Heinz', (select id from public.categories where name = 'Snacks'), 'Cashews, almonds, macadamias, pecans and Brazil nuts. Lightly salted.', 'Cashews, almonds, macadamia nuts, pecans, Brazil nuts, peanut oil, sea salt', '', array['planters', 'mixed nuts', 'nuts', 'snacks', 'cashews', 'almonds', 'healthy']::text[], 80, 52, 38, 60),
  (18, '038000845598', 'Pringles Original 5.2oz', 'Kellanova', (select id from public.categories where name = 'Snacks'), 'Stackable potato crisps with original seasoning. Non-recyclable composite can.', 'Dried potatoes, vegetable oil (corn, cottonseed, high oleic soybean, and/or sunflower oil), degerminated yellow corn flour, cornstarch, rice flour, maltodextrin, mono and diglycerides, salt, wheat starch', '', array['pringles', 'potato chips', 'crisps', 'stackable', 'snacks', 'original']::text[], 42, 35, 52, 52),
  (19, '030000010793', 'Quaker Instant Oatmeal Variety Pack 12ct', 'PepsiCo', (select id from public.categories where name = 'Breakfast'), 'Quick-cooking oats in convenient single-serve packets. Variety pack with maple, brown sugar, and apple cinnamon.', 'Whole grain rolled oats, sugar, natural and artificial flavors, salt, calcium carbonate, guar gum, niacinamide, B vitamins', '', array['quaker', 'oatmeal', 'breakfast', 'instant oats', 'hot cereal', 'whole grain', 'oats']::text[], 72, 62, 58, 68),
  (20, '038000131738', 'Kellogg''s Special K Original 13oz', 'Kellanova', (select id from public.categories where name = 'Breakfast'), 'Lightly sweetened rice and wheat flakes fortified with 8 essential vitamins and minerals.', 'Rice, wheat gluten, sugar, defatted wheat germ, salt, high fructose corn syrup, iron, B vitamins', '', array['special k', 'kelloggs', 'cereal', 'breakfast', 'diet cereal', 'low calorie']::text[], 65, 52, 55, 62),
  (21, '817939010162', 'Method All-Purpose Cleaner 28oz', 'SC Johnson', (select id from public.categories where name = 'Cleaning'), 'Plant-derived all-purpose cleaner. EPA Safer Choice certified. Carbon-neutral packaging.', 'Water, sodium lauryl sulfate (plant-derived), lauramine oxide, sodium citrate, methylpropanediol, fragrance (essential oils)', '', array['method', 'all purpose cleaner', 'cleaning', 'natural cleaner', 'eco', 'plant based']::text[], 85, 88, 82, 88),
  (22, '044600300247', 'Clorox Regular Bleach 81oz', 'The Clorox Company', (select id from public.categories where name = 'Cleaning'), 'Disinfecting bleach for laundry and household surfaces. 6% sodium hypochlorite.', 'Sodium hypochlorite (6%), sodium chloride, sodium carbonate, sodium hydroxide, water', '', array['clorox', 'bleach', 'cleaning', 'disinfectant', 'laundry bleach']::text[], 35, 42, 62, 65),
  (23, '037000879657', 'Dawn Ultra Original Dish Soap 19.4oz', 'Procter & Gamble', (select id from public.categories where name = 'Cleaning'), 'Concentrated dish soap that cuts through grease. Original blue formula.', 'Water, sodium lauryl sulfate, lauramine oxide, sodium chloride, PPG-26, PEG-8 propylheptyl ether, fragrance, methylisothiazolinone, polyethylenimine ethoxylated', '', array['dawn', 'dish soap', 'cleaning', 'dishwashing', 'grease cutting', 'blue']::text[], 50, 48, 45, 50),
  (24, '011111022704', 'Dove Beauty Bar Original 6pk', 'Unilever', (select id from public.categories where name = 'Personal Care'), 'Moisturizing beauty bar with 1/4 moisturizing cream. Mild and gentle for daily use.', 'Sodium lauroyl isethionate, stearic acid, sodium tallowate or sodium palmitate, lauric acid, sodium isethionate, water, sodium stearate, cocamidopropyl betaine, fragrance, glycerin, titanium dioxide', '', array['dove', 'beauty bar', 'soap', 'personal care', 'moisturizing', 'gentle']::text[], 72, 65, 65, 68),
  (25, '035000015861', 'Colgate Total Whitening Toothpaste 4pk', 'Colgate-Palmolive', (select id from public.categories where name = 'Personal Care'), 'Fluoride toothpaste providing 12-hour antibacterial protection. Whitening formula.', 'Sodium fluoride, water, hydrated silica, sorbitol, glycerin, PVM/MA copolymer, sodium lauryl sulfate, cellulose gum, sodium hydroxide, carrageenan, flavor, titanium dioxide', '', array['colgate', 'toothpaste', 'dental', 'oral care', 'fluoride', 'whitening', 'personal care']::text[], 65, 50, 62, 65),
  (26, '037000222767', 'Head & Shoulders Classic Clean Shampoo 23.7oz', 'Procter & Gamble', (select id from public.categories where name = 'Personal Care'), 'Anti-dandruff shampoo with 1% pyrithione zinc. Controls dandruff from first use.', 'Water, sodium lauryl sulfate, sodium laureth sulfate, zinc pyrithione, dimethicone, sodium chloride, glycol distearate, cocamide MEA, fragrance, sodium xylenesulfonate', '', array['head and shoulders', 'shampoo', 'dandruff', 'hair care', 'personal care', 'zinc pyrithione']::text[], 52, 42, 42, 48),
  (27, '070501006074', 'Neutrogena Ultra Sheer Sunscreen SPF 55 3oz', 'Johnson & Johnson', (select id from public.categories where name = 'Personal Care'), 'Lightweight broad spectrum UVA/UVB sunscreen. Non-comedogenic and non-greasy.', 'Homosalate, oxybenzone, octisalate, octocrylene, avobenzone, water, glycerin, styrene/acrylates copolymer, dimethicone, tocopheryl acetate, glyceryl stearate, fragrance', '', array['neutrogena', 'sunscreen', 'spf', 'sun protection', 'personal care', 'uvb', 'uva']::text[], 60, 52, 58, 65),
  (28, '037000741831', 'Pantene Pro-V Moisture Mend Shampoo 27.7oz', 'Procter & Gamble', (select id from public.categories where name = 'Personal Care'), 'Strengthening shampoo for damaged hair. Pro-V formula with silicone conditioning.', 'Water, sodium lauryl sulfate, sodium laureth sulfate, dimethicone, glycol distearate, sodium chloride, DMDM hydantoin, fragrance, citric acid, methylchloroisothiazolinone', '', array['pantene', 'shampoo', 'hair care', 'personal care', 'moisture', 'pro-v']::text[], 50, 40, 42, 48),
  (29, '305210201007', 'Vaseline Original Petroleum Jelly 13oz', 'Unilever', (select id from public.categories where name = 'Personal Care'), 'Triple-purified petroleum jelly. Seals in moisture and helps heal dry skin.', '100% White Petrolatum (petroleum jelly)', '', array['vaseline', 'petroleum jelly', 'skin care', 'moisturizer', 'personal care', 'healing']::text[], 78, 50, 62, 75),
  (30, '037000856092', 'Secret Clinical Strength Antiperspirant 1.6oz', 'Procter & Gamble', (select id from public.categories where name = 'Personal Care'), '48-hour clinical strength sweat protection with aluminum zirconium.', 'Aluminum zirconium tetrachlorohydrex GLY, cyclopentasiloxane, stearyl alcohol, PPG-14 butyl ether, hydrogenated castor oil, fragrance, propylene carbonate, bentonite', '', array['secret', 'antiperspirant', 'deodorant', 'personal care', 'clinical strength']::text[], 40, 35, 42, 40),
  (31, '047400230468', 'Gillette Fusion5 Men''s Razor + 2 Blade Refills', 'Procter & Gamble', (select id from public.categories where name = 'Personal Care'), '5-blade razor with precision trimmer. Lubristrip for smooth glide.', 'Handle (ABS plastic, stainless steel), blades (high-chromium stainless steel), lubristrip (polyethylene glycol, fatty acid blend)', '', array['gillette', 'razor', 'shaving', 'personal care', 'fusion', 'blades']::text[], 82, 32, 42, 55),
  (32, '021000013617', 'Kraft Singles American Cheese 16 Slices', 'Kraft Heinz', (select id from public.categories where name = 'Dairy'), 'Individually wrapped processed cheese product. Melts smoothly for grilled cheese and burgers.', 'Skim milk, milk, water, whey, milkfat, milk protein concentrate, salt, calcium phosphate, sodium citrate, sodium phosphate, lactic acid, annatto and paprika extract (color), cheese culture, enzymes, Vitamin D3', '', array['kraft singles', 'american cheese', 'cheese', 'dairy', 'processed cheese', 'sliced']::text[], 38, 35, 38, 48),
  (33, '070470004084', 'Yoplait Original Strawberry Yogurt 6oz', 'General Mills', (select id from public.categories where name = 'Dairy'), 'Low-fat yogurt with live and active cultures. Strawberry flavored with real fruit.', 'Cultured pasteurized grade A low fat milk, strawberries, sugar, modified corn starch, kosher gelatin, tricalcium phosphate, natural flavor, pectin, vitamin D3, live active cultures', '', array['yoplait', 'yogurt', 'strawberry', 'dairy', 'probiotics', 'low fat', 'cultured']::text[], 65, 55, 62, 65),
  (34, '041200000000', 'Land O''Lakes Salted Butter 1lb', 'Land O''Lakes', (select id from public.categories where name = 'Dairy'), 'Rich, creamy salted butter from a farmer-owned cooperative. Sweet cream butter with sea salt.', 'Cream, salt', '', array['land o lakes', 'butter', 'dairy', 'salted butter', 'cream', 'baking']::text[], 60, 42, 72, 75),
  (35, '742365003009', 'Horizon Organic Whole Milk Half Gallon', 'Danone', (select id from public.categories where name = 'Dairy'), 'USDA certified organic whole milk from pasture-raised cows. No added hormones or antibiotics.', 'Organic whole milk, vitamin D3', '', array['horizon', 'organic milk', 'whole milk', 'dairy', 'organic', 'pasture raised', 'vitamin d']::text[], 82, 72, 75, 80),
  (36, '037600101387', 'SPAM Classic 12oz', 'Hormel Foods', (select id from public.categories where name = 'Meat'), 'Canned cooked pork with ham. A global comfort food since 1937.', 'Pork with ham, salt, water, potato starch, sugar, sodium nitrite', '', array['spam', 'canned meat', 'pork', 'meat', 'protein', 'classic', 'hormel']::text[], 22, 28, 32, 45),
  (37, '023700012572', 'Tyson Fully Cooked Chicken Nuggets 32oz', 'Tyson Foods', (select id from public.categories where name = 'Meat'), 'Breaded white meat chicken nuggets. Fully cooked and ready in minutes.', 'Chicken, water, salt, sodium phosphates; breading: enriched flour, yellow corn flour, salt, leavening, spice, yeast extract, natural flavor, wheat starch', '', array['tyson', 'chicken nuggets', 'frozen chicken', 'meat', 'poultry', 'processed chicken']::text[], 38, 28, 28, 38),
  (38, '077200013403', 'Jimmy Dean Original Pork Sausage Roll 16oz', 'Tyson Foods', (select id from public.categories where name = 'Meat'), 'Classic pork breakfast sausage. Seasoned with signature blend of sage and spices.', 'Pork, water, salt, spices, sugar, BHA', '', array['jimmy dean', 'sausage', 'breakfast sausage', 'pork', 'meat', 'morning']::text[], 25, 25, 28, 38),
  (39, '048000228091', 'StarKist Chunk Light Tuna in Water 5oz', 'StarKist / Dongwon', (select id from public.categories where name = 'Meat'), 'Dolphin safe chunk light tuna packed in water. High protein and low fat.', 'Tuna, water, vegetable broth, salt', '', array['starkist', 'tuna', 'canned tuna', 'seafood', 'protein', 'fish', 'light tuna']::text[], 72, 55, 52, 62),
  (40, '044000852269', 'Wonder Classic White Bread 20oz', 'Flowers Foods', (select id from public.categories where name = 'Bread'), 'Soft white sandwich bread enriched with calcium and vitamins.', 'Enriched flour, water, sugar, yeast, soybean oil, salt, calcium sulfate, monocalcium phosphate, calcium propionate, sodium stearoyl lactylate, mono and diglycerides, DATEM, B vitamins', '', array['wonder bread', 'white bread', 'bread', 'sandwich bread', 'bakery', 'sliced bread']::text[], 42, 45, 52, 52),
  (41, '014100085102', 'Pepperidge Farm Goldfish Cheddar 30oz Carton', 'Campbell Soup Company', (select id from public.categories where name = 'Snacks'), 'Baked cheddar cheese crackers made with real cheese. A lunchbox classic.', 'Enriched wheat flour, cheddar cheese (pasteurized milk, cheese cultures, salt, enzymes), nonfat milk, vegetable oils (canola, sunflower, palm), contains 2% or less of: salt, yeast, baking soda, natural flavors', '', array['goldfish', 'pepperidge farm', 'crackers', 'cheese crackers', 'snacks', 'kids snack', 'cheddar']::text[], 62, 52, 58, 62),
  (42, '070038324225', 'DiGiorno Rising Crust Pepperoni Pizza 27.5oz', 'Nestle', (select id from public.categories where name = 'Frozen'), 'Classic rising crust frozen pizza with pepperoni and mozzarella cheese.', 'Enriched flour, water, pepperoni (pork, beef, salt, spices, sodium nitrite), mozzarella cheese, tomato paste, sugar, soybean oil, yeast, salt, reduced fat mozzarella cheese', '', array['digiorno', 'pizza', 'frozen pizza', 'pepperoni', 'mozzarella', 'rising crust', 'frozen food']::text[], 32, 30, 38, 42),
  (43, '013800006479', 'Stouffer''s Macaroni & Cheese 12oz', 'Nestle', (select id from public.categories where name = 'Frozen'), 'Creamy baked macaroni and cheese made with real cheddar cheese sauce.', 'Cooked enriched macaroni, skim milk, cheddar cheese, water, modified food starch, butter, cream, salt, sodium phosphate, artificial flavor', '', array['stouffers', 'mac and cheese', 'macaroni', 'frozen meal', 'comfort food', 'cheddar', 'frozen food']::text[], 40, 32, 38, 45),
  (44, '076840001049', 'Ben & Jerry''s Chocolate Chip Cookie Dough 16oz', 'Unilever', (select id from public.categories where name = 'Frozen'), 'Vermont''s finest ice cream with cookie dough chunks and chocolate chips.', 'Cream, skim milk, liquid sugar, water, wheat flour, sugar, chocolate chip cookie dough, butter, eggs, vanilla, B vitamins', '', array['ben and jerrys', 'ice cream', 'cookie dough', 'chocolate chip', 'frozen dessert', 'vermont', 'fair trade']::text[], 35, 58, 65, 72),
  (45, '013000004015', 'Heinz Tomato Ketchup 32oz', 'Kraft Heinz', (select id from public.categories where name = 'Condiments'), 'The original tomato ketchup. Made with vine-ripened tomatoes and spices.', 'Tomato concentrate, distilled vinegar, high fructose corn syrup, corn syrup, salt, spice, onion powder, natural flavoring', '', array['heinz', 'ketchup', 'condiment', 'tomato ketchup', 'sauce']::text[], 55, 48, 42, 55),
  (46, '048001214779', 'Hellmann''s Real Mayonnaise 30oz', 'Unilever', (select id from public.categories where name = 'Condiments'), 'Made with real, simple ingredients. Cage-free eggs and responsibly sourced soybean oil.', 'Soybean oil, water, whole eggs and egg yolks, vinegar, salt, sugar, lemon juice concentrate, calcium disodium EDTA', '', array['hellmanns', 'mayonnaise', 'mayo', 'condiment', 'real mayo', 'eggs']::text[], 62, 52, 60, 60),
  (47, '041500058069', 'French''s Classic Yellow Mustard 14oz', 'McCormick & Company', (select id from public.categories where name = 'Condiments'), 'Classic yellow mustard with vinegar and turmeric. No artificial colors or flavors.', 'Distilled vinegar, water, #1 grade mustard seed, salt, turmeric, paprika, spice, garlic powder, natural flavors and extractives of paprika', '', array['frenchs', 'mustard', 'yellow mustard', 'condiment', 'classic mustard', 'turmeric']::text[], 78, 62, 68, 72),
  (48, '037000868293', 'Pampers Sensitive Baby Wipes 504ct', 'Procter & Gamble', (select id from public.categories where name = 'Baby Care'), 'Hypoallergenic wipes with aloe and vitamin E. Gentle enough for newborns.', 'Water, polysorbate-20, sodium benzoate, aloe barbadensis leaf extract, tocopheryl acetate (vitamin E), citric acid', '', array['pampers', 'baby wipes', 'sensitive wipes', 'baby care', 'diaper wipes', 'hypoallergenic']::text[], 70, 35, 52, 60),
  (49, '015000007083', 'Gerber Graduates Puffs Strawberry Apple 1.48oz', 'Nestle', (select id from public.categories where name = 'Baby Care'), 'Lightly flavored whole grain puffs for babies 8+ months. Melts easily in mouth.', 'Whole wheat flour, whole grain oat flour, sugar, wheat starch, apple juice concentrate, natural strawberry flavor, vitamin E', '', array['gerber', 'baby puffs', 'baby snacks', 'baby food', 'strawberry apple', 'graduates', 'infant']::text[], 80, 60, 52, 68),
  (50, '300450449989', 'Tylenol Extra Strength Caplets 100ct', 'Johnson & Johnson', (select id from public.categories where name = 'Medicine'), 'Acetaminophen 500mg. Temporary relief of minor aches and pains. Reduces fever.', 'Acetaminophen 500mg; inactive: corn starch, hypromellose, magnesium stearate, polyethylene glycol, powdered cellulose, sodium starch glycolate, titanium dioxide', '', array['tylenol', 'acetaminophen', 'pain relief', 'medicine', 'fever reducer', 'headache', 'otc']::text[], 70, 55, 62, 75),
  (51, '017800185165', 'Purina ONE SmartBlend Chicken & Rice Dog Food 8lb', 'Nestle Purina', (select id from public.categories where name = 'Pet Food'), 'Real chicken is the #1 ingredient. Supports strong muscles and a healthy coat.', 'Chicken, brewers rice, corn gluten meal, whole grain corn, poultry by-product meal, soy flakes, oat meal, fish meal, calcium carbonate, vitamin and mineral supplements', '', array['purina one', 'dog food', 'pet food', 'chicken', 'rice', 'dry dog food', 'adult dog']::text[], 72, 48, 55, 65);

insert into public.product_prices (product_id, store, price, rating, condition) values
  (1, 'amazon', 3.98, 4.5, null),
  (1, 'walmart', 3.48, 4.3, null),
  (1, 'facebook', 2, null, 'Unopened'),
  (2, 'amazon', 13.97, 4.8, null),
  (2, 'walmart', 12.94, 4.7, null),
  (2, 'facebook', 10, null, 'Partial box'),
  (3, 'amazon', 14.99, 4.6, null),
  (3, 'walmart', 13.88, 4.5, null),
  (4, 'amazon', 18.99, 4.7, null),
  (4, 'walmart', 16.98, 4.6, null),
  (4, 'facebook', 12, null, 'Sealed case'),
  (5, 'amazon', 18.49, 4.4, null),
  (5, 'walmart', 17.97, 4.3, null),
  (6, 'amazon', 5.99, 4.2, null),
  (6, 'walmart', 4.98, 4.1, null),
  (6, 'facebook', 3.5, null, 'Fresh'),
  (7, 'amazon', 7.99, 4.5, null),
  (7, 'walmart', 6.98, 4.4, null),
  (7, 'facebook', 5, null, 'Sealed'),
  (8, 'amazon', 8.99, 4.6, null),
  (8, 'walmart', 7.48, 4.5, null),
  (9, 'amazon', 5.49, 4.5, null),
  (9, 'walmart', 4.98, 4.4, null),
  (10, 'amazon', 10.99, 4.4, null),
  (10, 'walmart', 9.98, 4.3, null),
  (10, 'facebook', 8, null, 'Sealed case'),
  (11, 'amazon', 1.29, 4.7, null),
  (11, 'walmart', 1.15, 4.6, null),
  (12, 'amazon', 11.49, 4.5, null),
  (12, 'walmart', 10.98, 4.4, null),
  (13, 'amazon', 5.98, 4.6, null),
  (13, 'walmart', 4.98, 4.5, null),
  (14, 'amazon', 4.49, 4.7, null),
  (14, 'walmart', 3.98, 4.6, null),
  (14, 'facebook', 3, null, 'Sealed'),
  (15, 'amazon', 4.49, 4.5, null),
  (15, 'walmart', 3.98, 4.4, null),
  (16, 'amazon', 5.99, 4.5, null),
  (16, 'walmart', 5.48, 4.4, null),
  (17, 'amazon', 12.99, 4.6, null),
  (17, 'walmart', 11.48, 4.5, null),
  (18, 'amazon', 2.99, 4.5, null),
  (18, 'walmart', 2.48, 4.4, null),
  (18, 'facebook', 2, null, 'Unopened'),
  (19, 'amazon', 5.49, 4.6, null),
  (19, 'walmart', 4.98, 4.5, null),
  (20, 'amazon', 4.99, 4.4, null),
  (20, 'walmart', 4.48, 4.3, null),
  (21, 'amazon', 5.99, 4.7, null),
  (21, 'walmart', 5.48, 4.6, null),
  (22, 'amazon', 4.99, 4.3, null),
  (22, 'walmart', 4.48, 4.2, null),
  (23, 'amazon', 3.99, 4.6, null),
  (23, 'walmart', 3.48, 4.5, null),
  (24, 'amazon', 9.99, 4.7, null),
  (24, 'walmart', 8.98, 4.6, null),
  (25, 'amazon', 10.49, 4.6, null),
  (25, 'walmart', 9.98, 4.5, null),
  (26, 'amazon', 8.99, 4.5, null),
  (26, 'walmart', 7.98, 4.4, null),
  (27, 'amazon', 10.99, 4.6, null),
  (27, 'walmart', 9.98, 4.5, null),
  (28, 'amazon', 7.99, 4.4, null),
  (28, 'walmart', 6.98, 4.3, null),
  (29, 'amazon', 8.99, 4.8, null),
  (29, 'walmart', 7.98, 4.7, null),
  (30, 'amazon', 10.99, 4.4, null),
  (30, 'walmart', 9.98, 4.3, null),
  (31, 'amazon', 12.99, 4.5, null),
  (31, 'walmart', 11.98, 4.4, null),
  (32, 'amazon', 4.49, 4.3, null),
  (32, 'walmart', 3.98, 4.2, null),
  (33, 'amazon', 1.29, 4.5, null),
  (33, 'walmart', 1.09, 4.4, null),
  (34, 'amazon', 5.49, 4.6, null),
  (34, 'walmart', 4.98, 4.5, null),
  (35, 'amazon', 7.99, 4.7, null),
  (35, 'walmart', 7.48, 4.6, null),
  (36, 'amazon', 3.99, 4.2, null),
  (36, 'walmart', 3.48, 4.1, null),
  (36, 'facebook', 2.5, null, 'Unopened'),
  (37, 'amazon', 10.99, 4.3, null),
  (37, 'walmart', 9.98, 4.2, null),
  (38, 'amazon', 6.99, 4.2, null),
  (38, 'walmart', 5.98, 4.1, null),
  (39, 'amazon', 1.99, 4.5, null),
  (39, 'walmart', 1.69, 4.4, null),
  (39, 'facebook', 1.25, null, 'Sealed 6-pack'),
  (40, 'amazon', 3.49, 4.2, null),
  (40, 'walmart', 2.98, 4.1, null),
  (41, 'amazon', 9.99, 4.7, null),
  (41, 'walmart', 8.98, 4.6, null),
  (42, 'amazon', 9.99, 4.4, null),
  (42, 'walmart', 8.98, 4.3, null),
  (43, 'amazon', 4.99, 4.3, null),
  (43, 'walmart', 4.48, 4.2, null),
  (44, 'amazon', 5.99, 4.8, null),
  (44, 'walmart', 5.49, 4.7, null),
  (45, 'amazon', 4.49, 4.6, null),
  (45, 'walmart', 3.98, 4.5, null),
  (46, 'amazon', 5.99, 4.7, null),
  (46, 'walmart', 5.48, 4.6, null),
  (47, 'amazon', 2.99, 4.6, null),
  (47, 'walmart', 2.48, 4.5, null),
  (48, 'amazon', 19.99, 4.7, null),
  (48, 'walmart', 17.98, 4.6, null),
  (49, 'amazon', 2.99, 4.7, null),
  (49, 'walmart', 2.69, 4.6, null),
  (50, 'amazon', 12.99, 4.8, null),
  (50, 'walmart', 11.98, 4.7, null),
  (51, 'amazon', 22.99, 4.6, null),
  (51, 'walmart', 19.98, 4.5, null);

insert into public.resources (id, name, type, address, hours, phone, description, latitude, longitude, rating) values
  (1, 'Community Food Pantry', 'food-bank', '142 Oak Street', 'Mon–Fri 9am–5pm', '(555) 234-5678', 'Hot meals and dry goods. No ID required.', 41.878, -87.632, 4.8),
  (2, 'Second Harvest Hub', 'food-bank', '389 Maple Avenue', 'Daily 8am–7pm', '(555) 876-5432', 'Fresh produce and pantry staples. 200+ families weekly.', 41.886, -87.618, 4.6),
  (3, 'Goodwill Drop-Off', 'donation', '55 Central Boulevard', 'Mon–Sat 8am–8pm', '(555) 345-6789', 'Clothing, furniture, electronics. Tax receipt provided.', 41.892, -87.641, 4.3),
  (4, 'Habitat ReStore', 'donation', '201 Pine Road', 'Tue–Sat 9am–6pm', '(555) 456-7890', 'Home improvement items and appliances.', 41.87, -87.646, 4.4),
  (5, 'Winter Warmth Drive', 'clothing', '78 Elm Street', 'Wed–Sun 10am–4pm', '(555) 567-8901', 'Coats, hats, and warm clothing for all ages.', 41.882, -87.625, 4.7),
  (6, 'Thread & Share Co-op', 'clothing', '315 Birch Way', 'Mon, Wed, Fri 12–6pm', '(555) 678-9012', 'Free clothing exchange — take what you need.', 41.888, -87.614, 4.5),
  (7, 'Community Bike Shop', 'bike-repair', '92 River Drive', 'Sat–Sun 10am–3pm', '(555) 789-0123', 'Free repairs, tire changes, and safety checks.', 41.875, -87.651, 4.9),
  (8, 'Pedal Forward Workshop', 'bike-repair', '420 Lake Avenue', 'Tue, Thu 4pm–8pm', '(555) 890-1234', 'DIY repair station with tools and spare parts.', 41.879, -87.621, 4.6),
  (9, 'City Hall Restrooms', 'restroom', '1 Civic Plaza', 'Mon–Fri 7am–9pm', null, 'Clean, accessible public restrooms. ADA compliant.', 41.883, -87.63, 3.9),
  (10, 'Central Park Facilities', 'restroom', 'Park Boulevard', 'Daily 6am–10pm', null, 'Restrooms and water fountains throughout the park.', 41.887, -87.636, 4.1),
  (11, 'Public Library WiFi', 'wifi', '250 Knowledge Drive', 'Mon–Sat 8am–8pm', '(555) 901-2345', 'High-speed internet. Computers available.', 41.891, -87.622, 4.7),
  (12, 'Community Center WiFi', 'wifi', '88 Unity Avenue', 'Daily 7am–11pm', '(555) 012-3456', 'Free WiFi, charging stations, and computer terminals.', 41.876, -87.629, 4.5),
  (13, 'Lincoln Park Garden', 'community-garden', 'Lincoln Park East', 'Daily dawn–dusk', null, 'Community vegetable and herb garden. Plots available.', 41.884, -87.642, 4.8),
  (14, 'Saturday Farmers Market', 'farmers-market', 'Civic Center Plaza', 'Sat 7am–1pm', '(555) 123-4567', 'Local produce, honey, eggs, and artisan goods.', 41.89, -87.627, 4.9),
  (15, 'FreshGo Community Grocer', 'grocery-store', '512 Grove Street', 'Daily 7am–10pm', '(555) 234-6789', 'Affordable groceries. EBT and WIC accepted.', 41.873, -87.639, 4.2),
  (16, 'Southside Health Clinic', 'health-clinic', '80 Wellness Way', 'Mon–Fri 8am–6pm', '(555) 345-7890', 'Free and sliding-scale primary care. No insurance required.', 41.88, -87.616, 4.6),
  (17, 'Second Story Thrift', 'thrift-store', '211 Commerce Avenue', 'Mon–Sat 9am–7pm', '(555) 456-8901', 'Quality second-hand clothing, books, and housewares.', 41.893, -87.633, 4.4),
  (18, 'GreenRoot Cooperative', 'sustainable-business', '44 Earth Lane', 'Mon–Sat 8am–8pm', '(555) 567-9012', 'Worker-owned zero-waste grocery and supplies.', 41.869, -87.623, 4.8);

-- Explicit ids were used above; move the identity sequences past them.
select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products));
select setval(pg_get_serial_sequence('public.resources', 'id'), (select max(id) from public.resources));
