-- EcoGo! catalog schema: normalized replacement for the Figma Make kv_store.
--
--   categories 1──* products 1──* product_prices
--                      │
--                      └──* scan_events (product_id is null = unknown barcode)
--   resources (map + home "nearby resources")
--
-- Overall score and letter grade are NOT stored: the frontend scoring engine
-- (src/lib/scoring.ts) derives them from the four dimension scores.

-- ── Helpers ──────────────────────────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ── Tables ───────────────────────────────────────────────────────────────────

create table public.categories (
  id         integer generated by default as identity primary key,
  name       text not null unique check (name <> ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id                 integer generated by default as identity primary key,
  barcode            text unique check (barcode <> ''),
  name               text not null check (name <> ''),
  brand              text not null default '',
  category_id        integer references public.categories (id) on delete restrict,
  description        text not null default '',
  ingredients        text not null default '',
  image_url          text not null default '',
  keywords           text[] not null default '{}',
  health_score       smallint not null check (health_score between 0 and 100),
  environment_score  smallint not null check (environment_score between 0 and 100),
  ethics_score       smallint not null check (ethics_score between 0 and 100),
  transparency_score smallint not null check (transparency_score between 0 and 100),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index products_category_id_idx on public.products (category_id);

create table public.product_prices (
  product_id integer not null references public.products (id) on delete cascade,
  store      text not null check (store in ('amazon', 'walmart', 'facebook')),
  price      numeric(10, 2) not null check (price >= 0),
  rating     numeric(2, 1) check (rating between 0 and 5),
  condition  text, -- Facebook Marketplace listing condition only
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, store)
);

create table public.resources (
  id          integer generated by default as identity primary key,
  name        text not null check (name <> ''),
  type        text not null check (type in (
                'food-bank', 'community-garden', 'farmers-market', 'wifi',
                'restroom', 'bike-repair', 'donation', 'grocery-store',
                'health-clinic', 'thrift-store', 'sustainable-business', 'clothing')),
  address     text not null default '',
  hours       text not null default '',
  phone       text,
  description text not null default '',
  latitude    double precision not null check (latitude between -90 and 90),
  longitude   double precision not null check (longitude between -180 and 180),
  rating      numeric(2, 1) check (rating between 0 and 5),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Anonymous, insert-only log. Coordinates are rounded client-side to ~100 m.
create table public.scan_events (
  id         bigint generated always as identity primary key,
  barcode    text not null check (char_length(barcode) between 1 and 64),
  product_id integer references public.products (id) on delete set null,
  store      text check (store in ('amazon', 'walmart', 'facebook')),
  price      numeric(10, 2) check (price >= 0),
  latitude   numeric(6, 3) check (latitude between -90 and 90),
  longitude  numeric(6, 3) check (longitude between -180 and 180),
  scanned_at timestamptz not null default now(),
  check ((latitude is null) = (longitude is null))
);
create index scan_events_product_id_idx on public.scan_events (product_id);

create trigger set_updated_at before update on public.categories
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.products
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.product_prices
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.resources
  for each row execute function public.set_updated_at();

-- ── Access: grants decide which tables a role can reach, RLS which rows ─────

alter table public.categories     enable row level security;
alter table public.products       enable row level security;
alter table public.product_prices enable row level security;
alter table public.resources      enable row level security;
alter table public.scan_events    enable row level security;

revoke all on public.categories, public.products, public.product_prices,
              public.resources, public.scan_events
  from anon, authenticated;

-- Catalog: world-readable, writable only by service_role (dashboard / admin).
grant select on public.categories, public.products, public.product_prices, public.resources
  to anon, authenticated;
grant select, insert, update, delete
  on public.categories, public.products, public.product_prices, public.resources, public.scan_events
  to service_role;

create policy "Catalog is publicly readable" on public.categories
  for select to anon, authenticated using (true);
create policy "Catalog is publicly readable" on public.products
  for select to anon, authenticated using (true);
create policy "Catalog is publicly readable" on public.product_prices
  for select to anon, authenticated using (true);
create policy "Catalog is publicly readable" on public.resources
  for select to anon, authenticated using (true);

-- Scans: clients may only INSERT these columns (id and scanned_at are
-- server-assigned) and can never read scans back, so locations stay private.
grant insert (barcode, product_id, store, price, latitude, longitude)
  on public.scan_events to anon, authenticated;
create policy "Anyone can record a scan" on public.scan_events
  for insert to anon, authenticated with check (true);

-- ── Realtime: the app re-fetches the catalog when any of these change ───────

alter publication supabase_realtime
  add table public.products, public.product_prices, public.resources;
